name: flutter_pdf_viewer
description: A new Flutter project.
publish_to: none
version: 0.8.26+27
environment:
  sdk: ">=2.17.5 <3.0.0"
dependencies:
  advance_pdf_viewer: ^2.0.1
  cached_network_image: ^3.2.3
  camera: ^0.10.0+4
  clipboard: ^0.1.3
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  dotted_border: ^2.0.0+3
  dropdown_button2: ^1.9.2
  equatable: ^2.0.0
  expandable: ^5.0.1
  file_picker: ^5.2.2
  file_selector: ^0.9.2+2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_bootstrap: ^2.0.0
  flutter_dotenv: ^5.0.2
  flutter_isolate: ^2.0.3
  flutter_keyboard_visibility: ^5.4.0
  flutter_launcher_icons: ^0.11.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.14
  flutter_secure_storage: ^6.0.0
  flutter_statusbarcolor_ns: ^0.5.0
  flutter_svg: ^1.1.6
  fluttertoast: ^8.1.1
  font_awesome_flutter: ^10.2.1
  fullscreen: ^1.0.3
  google_fonts: ^3.0.1
  gradient_progress_indicator: ^1.0.0+1
  gradient_widgets: ^0.6.0
  hovering: ^1.0.4
  http: ^0.13.5
  http_mock_adapter: ^0.3.3
  image_crop: ^0.4.1
  image_cropper: ^3.0.1
  image_cropping: ^0.0.13
  image_picker: ^0.8.6
  intl: ^0.17.0
  linear_progress_bar: ^1.1.0
  loading_animation_widget: ^1.2.0+3
  logger: ^1.1.0
  material_design_icons_flutter: ^6.0.7096
  mocktail: ^0.3.0
  modal_bottom_sheet: ^2.1.2
  modal_side_sheet: ^0.0.1
  no_context_navigation: ^2.1.2
  number_pagination: ^0.0.3+2
  oktoast: ^3.3.1
  package_info_plus: ^3.0.2
  pagination: ^0.1.0
  path_provider: ^2.0.11
  pdfx: ^2.3.0
  percent_indicator: ^4.2.2
  permission_handler: ^10.2.0
  pin_code_fields: ^7.4.0
  reactive_forms: ^14.1.0
  responsive_layout_builder: ^0.5.0
  responsive_sizer: ^3.1.1
  restart_app: ^1.1.1
  simple_image_cropper: ^1.0.0
  socket_io_client: ^2.0.1
  steps_indicator: ^1.3.0
  tuple: ^2.0.1
  universal_html: ^2.0.8
  universal_io: ^2.0.4
  url_launcher: ^6.1.7
  very_good_analysis: ^3.1.0
  video_player: ^2.4.8
  web_socket_channel: ^2.2.0
  web_socket_client: ^0.1.0-dev.1
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter_icons:
  android: launcher_icon
  ios: true
  image_path: assets/logos/logomobile.png
flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/logos/
    - assets/icons/
  fonts:
    - family: open-sans
      fonts:
        - asset: fonts/open-sans/OpenSans-Regular.ttf
        - asset: fonts/open-sans/OpenSans-Italic.ttf
          style: italic
        - asset: fonts/open-sans/OpenSans-Bold.ttf
          weight: 700
    - family: nunito
      fonts:
        - asset: fonts/nunito/Nunito-Regular.ttf
        - asset: fonts/nunito/Nunito-Bold.ttf
          weight: 700
